name: plant_database
description: A Dart package for managing a plant database.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.9.0
resolution: workspace

# Add regular dependencies here.
dependencies:  
  yaml: ^3.1.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
dev_dependencies:
  json_serializable: ^6.11.1
  build_runner: ^2.5.0
  lints: ^6.0.0




